<?php

namespace App\Contexts\Commerce\Filament\Resources;

use App\Contexts\Commerce\Filament\Resources\InvoiceResource\Pages;
use App\Contexts\Commerce\Models\Invoice;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

/**
 * Read-only finance visibility into invoices. Invoices are generated by the commerce flow;
 * the admin views them (create/edit are disabled — never hand-authored).
 */
class InvoiceResource extends Resource
{
    protected static ?string $model = Invoice::class;

    protected static string|\BackedEnum|null $navigationIcon = 'heroicon-o-document-currency-dollar';

    protected static string|\UnitEnum|null $navigationGroup = 'Commerce';

    protected static ?string $navigationLabel = 'Invoices';

    public static function canCreate(): bool
    {
        return false;
    }

    public static function form(Schema $schema): Schema
    {
        return $schema->components([]);
    }

    public static function table(Table $table): Table
    {
        return $table->columns([
            TextColumn::make('number')->searchable()->sortable(),
            TextColumn::make('status')->badge()->toggleable(),
            TextColumn::make('total_minor')->label('Total (minor)')->sortable(),
            TextColumn::make('currency')->toggleable(),
            TextColumn::make('issued_at')->dateTime()->toggleable(),
            TextColumn::make('paid_at')->dateTime()->toggleable(),
        ])->defaultSort('id', 'desc');
    }

    public static function getPages(): array
    {
        return ['index' => Pages\ListInvoice::route('/')];
    }
}
